"""
Configuration Module
Contains scraping headers, websites list by topic, and YouTube channels list by topic.
"""

HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5',
    'Referer': 'https://www.google.com/'
}

SITES_BY_TOPIC = {
    '🔬 Science, Discovery & Natural World': [
        ('Quanta Magazine', 'https://www.quantamagazine.org/'),
        ('Science Daily', 'https://www.sciencedaily.com/'),
        ('Science Alert', 'https://www.sciencealert.com/'),
        ('Live Science', 'https://www.livescience.com/'),
        ('The Conversation', 'https://theconversation.com/'),
        ('JSTOR Daily', 'https://daily.jstor.org/'),
        ('Smithsonian Institution', 'https://www.si.edu/'),
        ('HowStuffWorks', 'https://www.howstuffworks.com/'),
        ('Damn Interesting', 'https://www.damninteresting.com/'),
        ('Nautilus Free Articles', 'https://nautil.us/'),
        ('Real Clear Science', 'https://www.realclearscience.com/'),
        ('Phys.org', 'https://phys.org/'),
    ],
    '🚀 Space & Astronomy': [
        ('NASA', 'https://www.nasa.gov/'),
        ('Space.com', 'https://www.space.com/'),
        ('EarthSky', 'https://earthsky.org/'),
        ('Sky & Telescope', 'https://skyandtelescope.org/'),
        ('The Planetary Society', 'https://www.planetary.org/'),
        ('Bad Astronomy (Phil Plait)', 'https://www.syfy.com/syfy-wire/bad-astronomy'),
    ],
    '🧠 Psychology, Behavior & the Mind': [
        ('Psychology Today', 'https://www.psychologytoday.com/'),
        ('Greater Good Magazine', 'https://greatergood.berkeley.edu/magazine'),
        ('BPS Research Digest', 'https://www.bps.org.uk/research-digest'),
        ('Behavioral Scientist', 'https://behavioralscientist.org/'),
        ('Neuroscience News', 'https://neurosciencenews.com/'),
        ('PsyPost', 'https://www.psypost.org/'),
        ('Simoly Psychology', 'https://www.simplypsychology.org/'),
    ],
    '📜 History & Archaeology': [
        ('Ancient History Encyclopedia (World History)', 'https://www.worldhistory.org/'),
        ('The History Blog', 'http://www.thehistoryblog.com/'),
        ('JSTOR Daily', 'https://daily.jstor.org/'),
        ('Archaeology Magazine', 'https://www.archaeology.org/'),
        ('Atlas Obscura', 'https://www.atlasobscura.com/'),
        ('HistoryNet', 'https://www.historynet.com/'),
        ("Lapham's Quarterly", 'https://www.laphamsquarterly.org/'),
    ],
    '💡 Philosophy, Ideas & Critical Thinking': [
        ('The Marginalian', 'https://www.themarginalian.org/'),
        ('Aeon Magazine', 'https://aeon.co/'),
        ('Philosophy Now', 'https://philosophynow.org/'),
        ('Internet Encyclopedia of Philosophy', 'https://iep.utm.edu/'),
        ('Stanford Encyclopedia of Philosophy', 'https://plato.stanford.edu/'),
        ('3 Quarks Daily', 'https://3quarksdaily.com/'),
        ('Farnam Street (FS)', 'https://fs.blog/'),
    ],
    '💰 Economics, Finance & Business': [
        ('Investopedia', 'https://www.investopedia.com/'),
        ('Planet Money (NPR)', 'https://www.npr.org/podcasts/510289/planet-money'),
        ('Marginal Revolution', 'https://marginalrevolution.com/'),
        ('ProMarket', 'https://promarket.org/'),
        ('VoxEU', 'https://cepr.org/voxeu'),
        ('Our World in Data', 'https://ourworldindata.org/'),
        ('Visual Capitalist', 'https://www.visualcapitalist.com/'),
        ('The Hustle', 'https://thehustle.co/'),
    ],
    '🌿 Environment, Climate & Ecology': [
        ('Mongabay', 'https://www.mongabay.com/'),
        ('Carbon Brief', 'https://www.carbonbrief.org/'),
        ('Inside Climate News', 'https://insideclimatenews.org/'),
        ('The Guardian Environment', 'https://www.theguardian.com/environment'),
        ('Yale Environment 360', 'https://e360.yale.edu/'),
        ('Hakai Magazine', 'https://hakaimagazine.com/'),
        ('Ensia', 'https://ensia.com/'),
    ],
    '🏥 Health, Medicine & Nutrition': [
        ('Harvard Health', 'https://www.health.harvard.edu/'),
        ('WebMD', 'https://www.webmd.com/'),
        ('Healthline', 'https://www.healthline.com/'),
        ('MedPage Today', 'https://www.medpagetoday.com/'),
        ('Examine.com', 'https://examine.com/'),
        ('Precision Nutrition', 'https://www.precisionnutrition.com/articles'),
        ('Nih MedlinePlus', 'https://medlineplus.gov/'),
        ('The BMJ (free articles)', 'https://www.bmj.com/'),
    ],
    '💻 Technology, Programming & AI': [
        ('Hacker News', 'https://news.ycombinator.com/'),
        ('MIT Technology Review', 'https://www.technologyreview.com/'),
        ('Ars Technica', 'https://arstechnica.com/'),
        ('The Verge', 'https://www.theverge.com/'),
        ('Wired', 'https://www.wired.com/'),
        ('Stack Overflow Blog', 'https://stackoverflow.blog/'),
        ('Dev.to', 'https://dev.to/'),
        ('CSS-Tricks', 'https://css-tricks.com/'),
        ('Smashing Magazine', 'https://www.smashingmagazine.com/'),
        ('A List Apart', 'https://alistapart.com/'),
        ('Two Minute Papers', 'https://www.youtube.com/c/K%C3%A1rolyZsolnai-Feh%C3%A9r'),
        ('Towards Data Science', 'https://towardsdatascience.com/'),
    ],
    '🔗 Blockchain, Web3 & Crypto': [
        ('CoinDesk', 'https://www.coindesk.com/'),
        ('CoinTelegraph', 'https://cointelegraph.com/'),
        ('Decrypt', 'https://decrypt.co/'),
        ('The Block', 'https://www.theblock.co/'),
        ('Bankless', 'https://www.bankless.com/'),
    ],
    '🎮 Gaming & Game Development': [
        ('Game Developer', 'https://www.gamedeveloper.com/'),
        ('80 Level', 'https://80.lv/'),
        ('Rock Paper Shotgun', 'https://www.rockpapershotgun.com/'),
        ('Polygon', 'https://www.polygon.com/'),
        ('PC Gamer', 'https://www.pcgamer.com/'),
        ('Kotaku', 'https://kotaku.com/'),
        ('Giant Bomb', 'https://www.giantbomb.com/'),
        ('Digital Foundry (Eurogamer)', 'https://www.eurogamer.net/digital-foundry'),
    ],
    '📖 Literature, Fiction & the Written Word': [
        ('Literary Hub', 'https://lithub.com/'),
        ('Reactor (Tor.com)', 'https://reactor.com/'),
        ('Clarkesworld Magazine', 'https://clarkesworldmagazine.com/'),
        ('The Millions', 'https://themillions.com/'),
        ('Electric Literature', 'https://electricliterature.com/'),
        ('Open Culture', 'https://www.openculture.com/'),
        ('Project Gutenberg', 'https://www.gutenberg.org/'),
        ('Standard Ebooks', 'https://standardebooks.org/'),
        ('Anime News Network', 'https://www.animenewsnetwork.com/'),
        ('NovelUpdates', 'https://www.novelupdates.com/'),
    ],
    '🎨 Design, Architecture & Visual Arts': [
        ('Designboom', 'https://www.designboom.com/'),
        ('Dezeen', 'https://www.dezeen.com/'),
        ('Core77', 'https://www.core77.com/'),
        ("It's Nice That", 'https://www.itsnicethat.com/'),
        ('Colossal', 'https://www.thisiscolossal.com/'),
        ('Brain Pickings (The Marginalian)', 'https://www.themarginalian.org/'),
        ('Creative Bloq', 'https://www.creativebloq.com/'),
        ('Behance', 'https://www.behance.net/'),
    ],
    '🎵 Music & Audio': [
        ('NME', 'https://www.nme.com/'),
        ('AV Club', 'https://www.avclub.com/'),
        ('Genius', 'https://genius.com/'),
        ('XXL Magazine', 'https://www.xxlmag.com/'),
        ('Consequence of Sound', 'https://consequence.net/'),
        ('Resident Advisor', 'https://ra.co/'),
        ('The Wire', 'https://www.thewire.co.uk/'),
        ('Sputnikmusic', 'https://www.sputnikmusic.com/'),
    ],
    '🎬 Film, TV & Cinema': [
        ('Little White Lies', 'https://lwlies.com/'),
        ('Roger Ebert (RogerEbert.com)', 'https://www.rogerebert.com/'),
        ('Letterboxd', 'https://letterboxd.com/'),
        ('Screen Rant', 'https://screenrant.com/'),
        ('IndieWire', 'https://www.indiewire.com/'),
        ('Criterion', 'https://www.criterion.com/current'),
        ('Film Comment', 'https://www.filmcomment.com/'),
    ],
    '🍽️ Food, Cooking & Gastronomy': [
        ('Serious Eats', 'https://www.seriouseats.com/'),
        ('The Food Lab (Kenji)', 'https://www.seriouseats.com/the-food-lab'),
        ('Bon Appétit', 'https://www.bonappetit.com/'),
        ('Epicurious', 'https://www.epicurious.com/'),
        ('Eater', 'https://www.eater.com/'),
        ('The Kitchn', 'https://www.thekitchn.com/'),
    ],
    '🌍 Travel, Geography & Culture': [
        ('Atlas Obscura', 'https://www.atlasobscura.com/'),
        ('Nomadic Matt', 'https://www.nomadicmatt.com/'),
        ('Condé Nast Traveler', 'https://www.cntraveler.com/'),
        ('The Culture Trip', 'https://theculturetrip.com/'),
        ('Roads & Kingdoms', 'https://roadsandkingdoms.com/'),
        ('Messy Nessy Chic', 'https://www.messynessy.com/'),
        ('Geo.fr', 'https://www.geo.fr/'),
    ],
    '🏋️ Sports, Fitness & Movement': [
        ('Bleacher Report', 'https://bleacherreport.com/'),
        ('The Athletic', 'https://theathletic.com/'),
        ('FiveThirtyEight', 'https://fivethirtyeight.com/'),
        ('Breaking Muscle', 'https://breakingmuscle.com/'),
        ('Renaissance Periodization', 'https://renaissanceperiodization.com/articles'),
        ('Runners World', 'https://www.runnersworld.com/'),
    ],
    '✏️ Writing, Language & Linguistics': [
        ('The Writing Cooperative', 'https://writingcooperative.com/'),
        ('Grammarist', 'https://grammarist.com/'),
        ('Lingua Franca (Chronicle)', 'https://www.chronicle.com/blogs/linguafranca'),
        ('Language Log', 'https://languagelog.ldc.upenn.edu/nll/'),
        ('The Paris Review — Craft Interviews', 'https://www.theparisreview.org/interviews'),
        ('Austin Kleon', 'https://austinkleon.com/'),
    ],
    '🔢 Mathematics & Logic': [
        ('Quanta Magazine — Math', 'https://www.quantamagazine.org/mathematics/'),
        ('3Blue1Brown', 'https://www.3blue1brown.com/'),
        ('Cut the Knot', 'https://www.cut-the-knot.org/'),
        ('Better Explained', 'https://betterexplained.com/'),
        ('MathWorld (Wolfram)', 'https://mathworld.wolfram.com/'),
        ('AMS Feature Column', 'https://www.ams.org/publicoutreach/feature-column/fc-current'),
    ],
    '🏛️ Politics, Society & Long-form Journalism': [
        ('ProPublica', 'https://www.propublica.org/'),
        ('The Intercept', 'https://theintercept.com/'),
        ('Foreign Policy', 'https://foreignpolicy.com/'),
        ('The Diplomat', 'https://thediplomat.com/'),
        ('Bellingcat', 'https://www.bellingcat.com/'),
        ('Rest of World', 'https://restofworld.org/'),
        ('The Markup', 'https://themarkup.org/'),
    ],
    '🌐 General Knowledge & Curiosity': [
        ('Mental Floss', 'https://www.mentalfloss.com/'),
        ('Curiosity', 'https://www.curiosity.com/'),
        ('The Art of Manliness', 'https://www.artofmanliness.com/'),
        ('Wait But Why', 'https://waitbutwhy.com/'),
        ('Kottke.org', 'https://kottke.org/'),
        ('Longreads', 'https://longreads.com/'),
        ('Pocket (curated)', 'https://getpocket.com/explore'),
        ('Arts & Letters Daily', 'https://www.aldaily.com/'),
    ],
    'Science & Technology': [
        ('Nature', 'https://www.nature.com/'),
        ('Scientific American', 'https://www.scientificamerican.com/'),
        ('New Scientist', 'https://www.newscientist.com/'),
        ('IEEE Xplore', 'https://ieeexplore.ieee.org/'),
        ('Nautilus', 'https://nautil.us/'),
        ('MIT Technology Review', 'https://www.technologyreview.com/'),
    ],
    'Music & Entertainment': [
        ('Pitchfork', 'https://pitchfork.com/'),
        ('Rolling Stone', 'https://www.rollingstone.com/'),
        ('The Athletic', 'https://theathletic.com/'),
        ('Sight & Sound (BFI)', 'https://www.bfi.org.uk/sight-and-sound'),
    ],
}

CHANNELS_BY_TOPIC = {
    'Science & Tech': [
        '@3blue1brown', '@numberphile', '@standupmaths', '@Mathologer', '@PrimerBlobs',
        '@Computerphile', '@SebastianLague', '@Fireship', '@TheCodingTrain', '@Reducible',
        '@TomScottGo', '@veritasium', '@kurzgesagt', '@pbsspacetime', '@minutephysics',
        '@upandatom', '@AntonPetrov', '@CrimePaysButBotanyDoesnt', '@journeytomicrocosmos',
        '@TierZoo', '@smartereveryday', '@SciShow', '@MedlifeCrisis', '@InstituteOfHumanAnatomy',
        '@WhatIveLearned', '@MarkRober', '@PracticalEngineering', '@StuffMadeHere',
        '@AppliedScience', '@ThisOldTony', '@TheB1M', '@OurChangingClimate', '@UndecidedMF',
        '@JustHaveaThink', '@Zenura', '@Psych2go', '@TEDEd',
        '@joescott', '@Vsauce', '@Exurb1a', '@stevemould', '@CaptainDisillusion'
    ],
    'Pop Culture & Gaming': [
        '@JacobGeller', '@XboxAhoy', '@GMTK', '@noclipvideo', '@PeopleMakeGames',
        '@gigguk', '@SuperEyepatchWolf', '@CanipEffect', '@mothersbasement',
        '@FoldingIdeas', '@patrickhwillems', '@Nerdwriter1', '@everyframeapainting',
        '@LessonsFromTheScreenplay', '@JustWrite', '@Sideways440', '@AdamNeely',
        '@12tonevideos', '@RickBeato', '@8bitMusicTheory', '@GreatArtExplained',
        '@theartassignment', '@OverlySarcasticProductions', '@kaptainkristian',
        '@hbomberguy', '@drewgooden', '@sarahzed', '@Artifexian', '@wisecrack',
        '@CuriousArchive', '@EmpLemon', '@JosephAndersonChannel', '@ContraPoints'
    ],
    'History, Geopolitics & Society': [
        '@Wendover', '@PolyMatter', '@HistoryMatters', '@Toldinstone', '@KingsandGenerals',
        '@RealEngineering', '@EconomicsExplained', '@CGPGrey', '@SecondThought',
        '@PlanetMoney', '@Einzelganger', '@theschooloflifeofficial', '@academyofideas',
        '@LikeStoriesofOld', '@TastingHistory', '@townsends', '@NotJustBikes',
        '@halfasinteresting', '@KentoBento', '@johnnyharris', '@Xidnaf',
        '@NativLang', '@Langfocus', '@RobWords', '@StewartHicks', '@Vox',
        '@stratechery', '@ColdFusion', '@HowMoneyWorks', '@slidebean',
        '@PatrickBoyleOnFinance', '@LegalEagle', '@FractalPhilosophy', '@Asianometry',
        '@CaspianReport'
    ],
    'Mysteries & Documentaries': [
        '@bellingcatofficial', '@InternetHistorian', '@Nexpo',
        '@LEMMiNO', '@FredrikKnudsen',
        '@Spoogli', '@Wendigoon', '@BarelySociable', '@AtrocityGuide', '@blameitonjorge',
        '@JCS', '@NickCrowley'
    ],
    'Other / Uncategorized': [
        '@CorridorCrew', '@JoshuaWeissman', '@EthanChlebowski', '@internetshaquille',
        '@KenjisCookingShow', '@FrenchGuyCooking', '@aragusea', '@ItaliaSquisita',
        '@bingingwithbabish', '@AbroadinJapan', '@theendlessadventure', '@baldandbankrupt',
        '@archdigest', '@kirstendirksen', '@DoctorMike', '@Watcher', '@Wendys',
        '@internetcommentetiquette', '@WayOutWestx2'
    ]
}

CHANNEL_FEEDS = {
    '@12tonevideos': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCTUtqcDkzw7bisadh6AOx5w',
    '@3blue1brown': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC1_uAIS3r8Vu6JjXWvastJg',
    '@8bitMusicTheory': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCeZLO2VgbZHeDcongKzzfOw',
    '@AbroadinJapan': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCuJn_2HhHRqnu3xiIukNx1Q',
    '@AdamNeely': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCnkp4xDOwqqJD7sSM3xdUiQ',
    '@AntonPetrov': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCE3TIAqAKtmtvPtiKaST9Zg',
    '@AppliedScience': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCcs0ZkP_as4PpHDhFcmCHyA',
    '@Artifexian': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC21W40YFzSs9imQYRXdaQKw',
    '@CGPGrey': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC2C_jShtL725hvbm1arSV9w',
    '@CanipEffect': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCz4ZjuO7HrynjRrRlur1yWg',
    '@ColdFusion': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCGkpFfEMF0eMJlh9xXj2lMw',
    '@Computerphile': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCoxcjq-8xIDTYp3uz647V5A',
    '@CorridorCrew': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCsn6cjffsvyOZCZxvGoJxGg',
    '@CrimePaysButBotanyDoesnt': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC3CBOpT2-NRvoc2ecFMDCsA',
    '@DoctorMike': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC0QHWhjbe5fGJEPz3sVb6nw',
    '@EconomicsExplained': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCVWX3F3DrTvDKa0LRilQoQQ',
    '@Einzelganger': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCePWm-O_zdgxr6dd4bcEg5A',
    '@EthanChlebowski': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCICdNqyJqyHB3_uDVtmFhPA',
    '@Fireship': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC2Xd-TjJByJyK2w1zNwY0zQ',
    '@FoldingIdeas': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCyNtlmLB73-7gtlBz00XOQQ',
    '@FrenchGuyCooking': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCPzFLpOblZEaIx2lpym1l1A',
    '@GMTK': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCqJ-Xo29CKyLTjn6z2XwYAw',
    '@GreatArtExplained': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC87WLm0IaVihJbsyrwH01jg',
    '@HistoryMatters': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC22BdTgxefuvUivrjesETjg',
    '@HowMoneyWorks': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCb9mpGh9PQjFXOG_irzrFoA',
    '@InstituteOfHumanAnatomy': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCuXD9pxa1936T8y3S_Y6G3Q',
    '@InternetHistorian': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC8Q7XEy86Q7T-3kNpNjYgwA',
    '@ItaliaSquisita': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCETyhmgxupv93Ix4VnIiQJQ',
    '@JacobGeller': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCfGA2WK6Rw-K1E_mn_gyW2g',
    '@JoshuaWeissman': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCUAg71CJEvFdOnujmep1Svw',
    '@JustHaveaThink': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCRBwLPbXGsI2cJe9W1zfSjQ',
    '@JustWrite': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCx0L2ZdYfiq-tsAXb8IXpQg',
    '@KenjisCookingShow': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCqqJQ_cXSat0KIAVfIfKkVA',
    '@KentoBento': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCi81W8s1vW-f7sYh8pG5Rmg',
    '@KingsandGenerals': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCCGvq-qmjFmmMD4e-PLQqGg',
    '@Langfocus': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCNhX3WQEkraW3VHPyup8jkQ',
    '@LegalEagle': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCpSUQewzOXg1F0zLmieKCqQ',
    '@LessonsFromTheScreenplay': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCXDIl5ElYimqmasGFGmp7Eg',
    '@LikeStoriesofOld': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCs7nPQIEba0T3tGOWWsZpJQ',
    '@MarkRober': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC513PdAP2-jWkJunTh5kXRw',
    '@Mathologer': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCH74Hc_7WYVzx1GXhLEH6Eg',
    '@MedlifeCrisis': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCgRBRE1DUP2w7HTH9j_L4OQ',
    '@NativLang': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCeCqpvJ2UCwC5PskCv_K5gQ',
    '@Nerdwriter1': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCJkMlOu7faDgqh4PfzbpLdg',
    '@Nexpo': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCzwtKPc68r580mPesHscivw',
    '@NotJustBikes': 'https://www.youtube.com/feeds/videos.xml?channel_id=UClhGRUBCbui0IKCAe-ezG3A',
    '@OurChangingClimate': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCAz17eZxF5tD7vNOEVgegKg',
    '@OverlySarcasticProductions': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCFQMO-YL87u-6Rt8hIVsRjA',
    '@PatrickBoyleOnFinance': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCASM0cgfkJxQ1ICmRilfHLw',
    '@PeopleMakeGames': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCZB6V9fUov0Mx_us3MWWILg',
    '@PlanetMoney': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCuVaB0t5qJRxP55gEl6TuKQ',
    '@PolyMatter': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCgNg3vwj3xt7QOrcIDaHdFg',
    '@PracticalEngineering': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCMOqf8ab-42UUQIdVoKwjlQ',
    '@PrimerBlobs': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCKzJFdi57J53Vr_BkTfN3uQ',
    '@Psych2go': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCkJEpR7JmS36tajD34Gp4VA',
    '@RealEngineering': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC176GAQozKKjhz62H8u9vQQ',
    '@Reducible': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCK8XIGR5kRidIw2fWqwyHRA',
    '@RickBeato': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCcp-HjtmTMeIJ-0RrSHSGLA',
    '@RobWords': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC4a9LfdavRlVMaSSWFdIciA',
    '@SciShow': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCUdettijNYvLAm4AixZv4RA',
    '@SebastianLague': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCmtyQOKKmrMVaKuRXz02jbQ',
    '@SecondThought': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCmd0Jb6TbFKEx1Of0yQu9fw',
    '@Sideways440': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCi7l9chXMljpUft67vw78qw',
    '@StewartHicks': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCYAm24PkejQR2xMgJgn7xwg',
    '@StuffMadeHere': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCNlBbEpwffgWefkbRm73xxQ',
    '@SuperEyepatchWolf': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCwodAmfPRunh2kEZw4pjeVA',
    '@TEDEd': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCAuUUnT6oDeKwE6v1NGQxug',
    '@TastingHistory': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCvvXKMlj_vWKzvTKpYbiWWg',
    '@TheB1M': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCN3aYbtQ7yCqk9DM56B0kEw',
    '@TheCodingTrain': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCeyJbY9g9spG7u8kfs2WrwQ',
    '@ThisOldTony': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC5NO8MgTQKHAWXp6z8Xl7yQ',
    '@TierZoo': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCHsRtomD4twRf5WVHHk-cMw',
    '@Toldinstone': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCytq3DBifaIwY376ARqdxWA',
    '@TomScottGo': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCBa659QWEk1AI4Tg--mrJ2A',
    '@UndecidedMF': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC4-aWB84Bupf5hxGqrwYqLA',
    '@Vox': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCLXo7UDZvByw2ixzpQCufnA',
    '@Watcher': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC9JApt_e3qEUxfb-drWR0nw',
    '@WayOutWestx2': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCp5y_KS72QmaK7aaWMil4q1Q',
    '@Wendover': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCvv8wDf6RC7swQ0j0GyS-vA',
    '@Wendys': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCxXHHbiGUO3RziA5kW0m1qw',
    '@WhatIveLearned': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCqYPhGiB9tkShZorfgcL2lA',
    '@XboxAhoy': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCE1jXbVAGJQEORz9nZqb5bQ',
    '@Xidnaf': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCByBOwwOU5tKddYpsrHiUUw',
    '@Zenura': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCnZFxbugfoQboLqFPTkQM-w',
    '@academyofideas': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC1KmNKYC1l0stjctkGswl6g',
    '@aragusea': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC9_p50tH3WmMslWRWKnM7dQ',
    '@archdigest': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC0k238zFx-Z8xFH0sxCrPJg',
    '@baldandbankrupt': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCB2GbNXOsy3VBksSD58NvhQ',
    '@bellingcatofficial': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCFl-GzKYeCW3iWjnQDuxzAA',
    '@bingingwithbabish': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC4avs5jYd_FvzQ8f0XYziqw',
    '@drewgooden': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCjtkaY_1JrDw6uUtwvcPsTg',
    '@everyframeapainting': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCjFqcJQXGZ6T6sxyFB-5i6A',
    '@gigguk': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCOv3Z7230GFKHdACf7zJleg',
    '@halfasinteresting': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC9RM-iSvTu1uPJb8X5yp3EQ',
    '@hbomberguy': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCIPqOTYW439-5hUz6r3U1fA',
    '@internetcommentetiquette': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCyWDyupW4lBq95hD0DkG4qg',
    '@internetshaquille': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCOcphUKAnUaair1uZ7SlqiA',
    '@johnnyharris': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC7KbIaEOuY7H2j-cvhJ3mYA',
    '@journeytomicrocosmos': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCBbnbBWJtwsf0jLGUwX5Q3g',
    '@kaptainkristian': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCuPgdqQKpq4T4zeqmTelnFg',
    '@kirstendirksen': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCDsElQQt_gCZ9LgnW-7v-cQ',
    '@kurzgesagt': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCq8ZAAsI89IoJ-fn1gYpO3g',
    '@minutephysics': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCeiYXex_fwgYDonaTcSIk6w',
    '@mothersbasement': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCiZhSNqcJqh8uFcY17gatdg',
    '@noclipvideo': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC0fDG3byEcMtbOqPMymDNbw',
    '@numberphile': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCtwKon9qMt5YLVgQt1tvJKg',
    '@patrickhwillems': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCMAwBUlaxyqZY-2hVac8qgg',
    '@pbsspacetime': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCq6OAftTQOuUBRdtUDq5SUA',
    '@sarahzed': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCsLQIZhIhTEskQSRi5y4IOw',
    '@slidebean': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCSGc7c1yKxo-Uhz5_oivrfg',
    '@smartereveryday': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC8VkNBOwvsTlFjoSnNSMmxw',
    '@standupmaths': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCSju5G2aFaWMqn-_0YBtq5A',
    '@stratechery': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC9AHywQeW9BOcOl7dg-YMqA',
    '@theartassignment': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCGaVdbSav8xWuFWTadK6loA',
    '@theendlessadventure': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCVZAfsaiMUbv50gz9TvMrZQ',
    '@theschooloflifeofficial': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC7IcJI8PUf5Z3zKxnZvTBog',
    '@townsends': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCj0yJUTrQvyLDeI3K5PLgyw',
    '@upandatom': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCQALLeQPoZdZC4JNUboVEUg',
    '@veritasium': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCin0m13qWv3-051xlWlHamA',
    '@wisecrack': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC6-PXcR7M7y4S4sB-e7rYSw',
    '@joescott': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCw-J55n8Y5Nn1fB19p0P0uQ',
    '@CuriousArchive': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCP12u_3r8xYlH8o9C42T-5g',
    '@Vsauce': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC6107grRI4m0o2-emgoDnAA',
    '@LEMMiNO': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCRcIdxmu0H1R4qY4s4Z8-3w',
    '@Exurb1a': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC_yP2PkR4oH6jLgUu27C76A',
    '@FredrikKnudsen': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCV19n4922h6m69g0p9LqPxg',
    '@FractalPhilosophy': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCxS4Zl5Y_gW8tU5uN-9_hXw',
    '@Spoogli': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC9Gt9zg0vsmh-21zwVN5epQ',
    '@Wendigoon': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCJkoT4_a87nU0eC_N-2N30A',
    '@BarelySociable': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC9PIn6-XuRKZ5HmYeu46AIw',
    '@AtrocityGuide': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCn8a-VvV-H0P67uO4w8y-eQ',
    '@blameitonjorge': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCU3oAyhHDXjgbxazqOEG2UA',
    '@stevemould': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCEIwxahdLz7bap-VDs9h35A',
    '@CaptainDisillusion': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCVjKN1Y-M98319fJqR1Z1zQ',
    '@EmpLemon': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC7Ucs42FZy3uYzjrqzOIHsw',
    '@JosephAndersonChannel': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCx4u4d03mQ1eWb6T-P-Jk8g',
    '@ContraPoints': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCNvsIonJdJ5E4EXMa65VYpA',
    '@Asianometry': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCnTuW5N0s4a3t87YqQ8t2MA',
    '@CaspianReport': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCp2-2U2m1nE8569lO2293iA',
    '@JCS': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCzXujqv02TfXyG1MhGZlKkA',
    '@NickCrowley': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCM47S9y1qVjWd8W5y84y8yA',
}
