"""
Configuration Module
Contains scraping headers, websites list by topic, and YouTube channels list by topic.
"""

HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5',
    'Referer': 'https://www.google.com/'
}

SITES_BY_TOPIC = {
    '🔬 Science, Discovery & Natural World': [
        ('Quanta Magazine', 'https://www.quantamagazine.org/'),
        ('Science Daily', 'https://www.sciencedaily.com/'),
        ('Science Alert', 'https://www.sciencealert.com/'),
        ('JSTOR Daily', 'https://daily.jstor.org/'),
        ('Damn Interesting', 'https://www.damninteresting.com/'),
        ('Nautilus', 'https://nautil.us/'),
    ],
    '🚀 Space & Astronomy': [
        ('Space.com', 'https://www.space.com/'),
        ('The Planetary Society', 'https://www.planetary.org/'),
    ],
    '🧠 Psychology, Behavior & the Mind': [
        ('Greater Good Magazine', 'https://greatergood.berkeley.edu/'),
        ('Behavioral Scientist', 'https://behavioralscientist.org/'),
        ('Neuroscience News', 'https://neurosciencenews.com/'),
        ('PsyPost', 'https://www.psypost.org/'),
    ],
    '📜 History & Archaeology': [
        ('Ancient History Encyclopedia (World History)', 'https://www.worldhistory.org/'),
        ('The History Blog', 'http://www.thehistoryblog.com/'),
        ('Archaeology Magazine', 'https://www.archaeology.org/'),
    ],
    '💡 Philosophy, Ideas & Critical Thinking': [
        ('The Marginalian', 'https://www.themarginalian.org/'),
        ('Aeon Magazine', 'https://aeon.co/'),
        ('Philosophy Now', 'https://philosophynow.org/'),
        ('3 Quarks Daily', 'https://3quarksdaily.com/'),
        ('Farnam Street (FS)', 'https://fs.blog/'),
    ],
    '🔢 Mathematics & Logic': [
        ('Quanta Magazine — Math', 'https://www.quantamagazine.org/mathematics/'),
        ('Better Explained', 'https://betterexplained.com/'),
    ],
    '🏛️ Politics, Society & Long-form Journalism': [
        ('ProPublica', 'https://www.propublica.org/'),
        ('The Diplomat', 'https://thediplomat.com/'),
        ('Bellingcat', 'https://www.bellingcat.com/'),
        ('Rest of World', 'https://restofworld.org/'),
    ],
    '📰 Magazines & Long-form Journalism': [
        ('The New Yorker', 'https://www.newyorker.com/'),
        ('The Atlantic', 'https://www.theatlantic.com/'),
        ('The Guardian', 'https://www.theguardian.com/'),
        ('Scientific American', 'https://www.scientificamerican.com/'),
        ('Smithsonian Magazine', 'https://www.smithsonianmag.com/'),
        ('MIT Technology Review', 'https://www.technologyreview.com/'),
        ('Wired', 'https://www.wired.com/'),
        ('National Geographic', 'https://www.nationalgeographic.com/'),
        ('The Paris Review', 'https://www.theparisreview.org/'),
        ('London Review of Books', 'https://www.lrb.co.uk/'),
        ('The New York Review of Books', 'https://www.nybooks.com/'),
        ('Sapiens', 'https://www.sapiens.org/'),
        ('The Conversation', 'https://theconversation.com/'),
    ],
    '🌿 Environment, Climate & Ecology': [
        ('Mongabay', 'https://www.mongabay.com/'),
        ('Yale Environment 360', 'https://e360.yale.edu/'),
        ('Hakai Magazine', 'https://hakaimagazine.com/'),
    ],
}

CHANNELS_BY_TOPIC = {
    'Science & Tech': [
        '@3blue1brown', '@numberphile', '@standupmaths', '@Mathologer', '@PrimerBlobs',
        '@Computerphile', '@SebastianLague', '@Fireship', '@TheCodingTrain', '@Reducible',
        '@TomScottGo', '@veritasium', '@kurzgesagt', '@pbsspacetime', '@minutephysics',
        '@upandatom', '@AntonPetrov', '@CrimePaysButBotanyDoesnt', '@journeytomicrocosmos',
        '@TierZoo', '@smartereveryday', '@SciShow', '@MedlifeCrisis', '@InstituteOfHumanAnatomy',
        '@WhatIveLearned', '@MarkRober', '@PracticalEngineering', '@StuffMadeHere',
        '@AppliedScience', '@ThisOldTony', '@TheB1M', '@OurChangingClimate', '@UndecidedMF',
        '@JustHaveaThink', '@Zenura', '@Psych2go', '@TEDEd',
        '@joescott', '@Vsauce', '@Exurb1a', '@stevemould', '@CaptainDisillusion',
        '@IBMTechnology', '@ScienceMaps', '@EmergentGarden'
    ],
    'Pop Culture & Gaming': [
        '@JacobGeller', '@XboxAhoy', '@GMTK', '@noclipvideo', '@PeopleMakeGames',
        '@gigguk', '@SuperEyepatchWolf', '@CanipEffect', '@mothersbasement',
        '@FoldingIdeas', '@patrickhwillems', '@Nerdwriter1', '@everyframeapainting',
        '@LessonsFromTheScreenplay', '@JustWrite', '@Sideways440', '@AdamNeely',
        '@12tonevideos', '@RickBeato', '@8bitMusicTheory', '@GreatArtExplained',
        '@theartassignment', '@OverlySarcasticProductions', '@kaptainkristian',
        '@hbomberguy', '@drewgooden', '@sarahzed', '@Artifexian', '@wisecrack',
        '@CuriousArchive', '@EmpLemon', '@JosephAndersonChannel', '@ContraPoints',
        '@isto_inc', '@TemplinInstitute', '@SolarSands', '@bunnyhopshow',
        '@WritingOnGames', '@ThomasFlight'
    ],
    'History, Geopolitics & Society': [
        '@Wendover', '@PolyMatter', '@HistoryMatters', '@Toldinstone', '@KingsandGenerals',
        '@RealEngineering', '@EconomicsExplained', '@CGPGrey', '@SecondThought',
        '@PlanetMoney', '@Einzelganger', '@theschooloflifeofficial', '@academyofideas',
        '@LikeStoriesofOld', '@TastingHistory', '@townsends', '@NotJustBikes',
        '@halfasinteresting', '@KentoBento', '@johnnyharris', '@Xidnaf',
        '@NativLang', '@Langfocus', '@RobWords', '@StewartHicks', '@Vox',
        '@stratechery', '@ColdFusion', '@HowMoneyWorks', '@slidebean',
        '@PatrickBoyleOnFinance', '@LegalEagle', '@FractalPhilosophy', '@Asianometry',
        '@CaspianReport', '@harvardbusinessreview', '@PhilosophyTube', '@InnuendoStudios',
        '@JonasCeikaCCK', '@Sisyphus55'
    ],
    'Mysteries & Documentaries': [
        '@bellingcatofficial', '@InternetHistorian', '@Nexpo',
        '@LEMMiNO', '@FredrikKnudsen',
        '@Spoogli', '@Wendigoon', '@BarelySociable', '@AtrocityGuide', '@blameitonjorge',
        '@JCS', '@NickCrowley'
    ],
    'Other / Uncategorized': [
        '@CorridorCrew', '@JoshuaWeissman', '@EthanChlebowski', '@internetshaquille',
        '@KenjisCookingShow', '@FrenchGuyCooking', '@aragusea', '@ItaliaSquisita',
        '@bingingwithbabish', '@AbroadinJapan', '@theendlessadventure', '@baldandbankrupt',
        '@archdigest', '@kirstendirksen', '@DoctorMike', '@Watcher', '@Wendys',
        '@internetcommentetiquette', '@WayOutWestx2'
    ]
}

CHANNEL_FEEDS = {
    '@12tonevideos': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCTUtqcDkzw7bisadh6AOx5w',
    '@3blue1brown': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC1_uAIS3r8Vu6JjXWvastJg',
    '@8bitMusicTheory': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCeZLO2VgbZHeDcongKzzfOw',
    '@AbroadinJapan': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCuJn_2HhHRqnu3xiIukNx1Q',
    '@AdamNeely': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCnkp4xDOwqqJD7sSM3xdUiQ',
    '@AntonPetrov': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCE3TIAqAKtmtvPtiKaST9Zg',
    '@AppliedScience': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCcs0ZkP_as4PpHDhFcmCHyA',
    '@Artifexian': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC21W40YFzSs9imQYRXdaQKw',
    '@CGPGrey': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC2C_jShtL725hvbm1arSV9w',
    '@CanipEffect': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCz4ZjuO7HrynjRrRlur1yWg',
    '@ColdFusion': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCGkpFfEMF0eMJlh9xXj2lMw',
    '@Computerphile': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCoxcjq-8xIDTYp3uz647V5A',
    '@CorridorCrew': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCsn6cjffsvyOZCZxvGoJxGg',
    '@CrimePaysButBotanyDoesnt': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC3CBOpT2-NRvoc2ecFMDCsA',
    '@DoctorMike': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC0QHWhjbe5fGJEPz3sVb6nw',
    '@EconomicsExplained': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCVWX3F3DrTvDKa0LRilQoQQ',
    '@Einzelganger': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCePWm-O_zdgxr6dd4bcEg5A',
    '@EmergentGarden': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCwBhBDsqiQflTMLy2epbQVw',
    '@EthanChlebowski': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCICdNqyJqyHB3_uDVtmFhPA',
    '@Fireship': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC2Xd-TjJByJyK2w1zNwY0zQ',
    '@FoldingIdeas': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCyNtlmLB73-7gtlBz00XOQQ',
    '@FrenchGuyCooking': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCPzFLpOblZEaIx2lpym1l1A',
    '@GMTK': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCqJ-Xo29CKyLTjn6z2XwYAw',
    '@GreatArtExplained': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC87WLm0IaVihJbsyrwH01jg',
    '@HistoryMatters': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC22BdTgxefuvUivrjesETjg',
    '@IBMTechnology': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCKWaEZ-_VweaEx1j62do_vQ',
    '@HowMoneyWorks': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCb9mpGh9PQjFXOG_irzrFoA',
    '@InstituteOfHumanAnatomy': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCuXD9pxa1936T8y3S_Y6G3Q',
    '@InnuendoStudios': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC5fdssPqmmGhkhsJi4VcckA',
    '@InternetHistorian': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC8Q7XEy86Q7T-3kNpNjYgwA',
    '@ItaliaSquisita': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCETyhmgxupv93Ix4VnIiQJQ',
    '@JacobGeller': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCfGA2WK6Rw-K1E_mn_gyW2g',
    '@JoshuaWeissman': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCUAg71CJEvFdOnujmep1Svw',
    '@JustHaveaThink': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCRBwLPbXGsI2cJe9W1zfSjQ',
    '@JustWrite': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCx0L2ZdYfiq-tsAXb8IXpQg',
    '@KenjisCookingShow': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCqqJQ_cXSat0KIAVfIfKkVA',
    '@KentoBento': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCi81W8s1vW-f7sYh8pG5Rmg',
    '@KingsandGenerals': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCCGvq-qmjFmmMD4e-PLQqGg',
    '@Langfocus': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCNhX3WQEkraW3VHPyup8jkQ',
    '@LegalEagle': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCpSUQewzOXg1F0zLmieKCqQ',
    '@LessonsFromTheScreenplay': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCXDIl5ElYimqmasGFGmp7Eg',
    '@LikeStoriesofOld': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCs7nPQIEba0T3tGOWWsZpJQ',
    '@MarkRober': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC513PdAP2-jWkJunTh5kXRw',
    '@Mathologer': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCH74Hc_7WYVzx1GXhLEH6Eg',
    '@MedlifeCrisis': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCgRBRE1DUP2w7HTH9j_L4OQ',
    '@NativLang': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCeCqpvJ2UCwC5PskCv_K5gQ',
    '@Nerdwriter1': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCJkMlOu7faDgqh4PfzbpLdg',
    '@Nexpo': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCzwtKPc68r580mPesHscivw',
    '@NotJustBikes': 'https://www.youtube.com/feeds/videos.xml?channel_id=UClhGRUBCbui0IKCAe-ezG3A',
    '@OurChangingClimate': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCAz17eZxF5tD7vNOEVgegKg',
    '@OverlySarcasticProductions': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCFQMO-YL87u-6Rt8hIVsRjA',
    '@PatrickBoyleOnFinance': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCASM0cgfkJxQ1ICmRilfHLw',
    '@PhilosophyTube': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC2PA-AKmVpU6NKCGtZq_rKQ',
    '@PeopleMakeGames': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCZB6V9fUov0Mx_us3MWWILg',
    '@PlanetMoney': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCuVaB0t5qJRxP55gEl6TuKQ',
    '@PolyMatter': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCgNg3vwj3xt7QOrcIDaHdFg',
    '@PracticalEngineering': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCMOqf8ab-42UUQIdVoKwjlQ',
    '@PrimerBlobs': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCKzJFdi57J53Vr_BkTfN3uQ',
    '@Psych2go': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCkJEpR7JmS36tajD34Gp4VA',
    '@RealEngineering': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC176GAQozKKjhz62H8u9vQQ',
    '@Reducible': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCK8XIGR5kRidIw2fWqwyHRA',
    '@RickBeato': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCcp-HjtmTMeIJ-0RrSHSGLA',
    '@RobWords': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC4a9LfdavRlVMaSSWFdIciA',
    '@SciShow': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCUdettijNYvLAm4AixZv4RA',
    '@ScienceMaps': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCxqAWLTk1CmBvZFPzeZMd9A',
    '@SolarSands': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCR6LasBpceuYUhuLToKBzvQ',
    '@SebastianLague': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCmtyQOKKmrMVaKuRXz02jbQ',
    '@SecondThought': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCmd0Jb6TbFKEx1Of0yQu9fw',
    '@Sideways440': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCi7l9chXMljpUft67vw78qw',
    '@Sisyphus55': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCDETFHKteb-C_EaXmRKvP4w',
    '@StewartHicks': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCYAm24PkejQR2xMgJgn7xwg',
    '@StuffMadeHere': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCNlBbEpwffgWefkbRm73xxQ',
    '@SuperEyepatchWolf': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCwodAmfPRunh2kEZw4pjeVA',
    '@TEDEd': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCAuUUnT6oDeKwE6v1NGQxug',
    '@TemplinInstitute': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCpqCsO-fb2_OzVxm7J9MslA',
    '@TastingHistory': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCvvXKMlj_vWKzvTKpYbiWWg',
    '@TheB1M': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCN3aYbtQ7yCqk9DM56B0kEw',
    '@TheCodingTrain': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCeyJbY9g9spG7u8kfs2WrwQ',
    '@ThisOldTony': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC5NO8MgTQKHAWXp6z8Xl7yQ',
    '@ThomasFlight': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCUyvQV2JsICeLZP4c_h40kA',
    '@TierZoo': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCHsRtomD4twRf5WVHHk-cMw',
    '@Toldinstone': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCytq3DBifaIwY376ARqdxWA',
    '@TomScottGo': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCBa659QWEk1AI4Tg--mrJ2A',
    '@UndecidedMF': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC4-aWB84Bupf5hxGqrwYqLA',
    '@Vox': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCLXo7UDZvByw2ixzpQCufnA',
    '@Watcher': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC9JApt_e3qEUxfb-drWR0nw',
    '@WayOutWestx2': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCp5y_KS72QmaK7aaWMil4q1Q',
    '@WritingOnGames': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCPlWv88ZRMxCcK3BGjrX7ew',
    '@Wendover': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCvv8wDf6RC7swQ0j0GyS-vA',
    '@Wendys': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCxXHHbiGUO3RziA5kW0m1qw',
    '@WhatIveLearned': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCqYPhGiB9tkShZorfgcL2lA',
    '@XboxAhoy': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCE1jXbVAGJQEORz9nZqb5bQ',
    '@Xidnaf': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCByBOwwOU5tKddYpsrHiUUw',
    '@Zenura': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCnZFxbugfoQboLqFPTkQM-w',
    '@academyofideas': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC1KmNKYC1l0stjctkGswl6g',
    '@aragusea': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC9_p50tH3WmMslWRWKnM7dQ',
    '@archdigest': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC0k238zFx-Z8xFH0sxCrPJg',
    '@baldandbankrupt': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCB2GbNXOsy3VBksSD58NvhQ',
    '@bellingcatofficial': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCFl-GzKYeCW3iWjnQDuxzAA',
    '@bunnyhopshow': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCWqr2tH3dPshNhPjV5h1xRw',
    '@bingingwithbabish': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC4avs5jYd_FvzQ8f0XYziqw',
    '@drewgooden': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCjtkaY_1JrDw6uUtwvcPsTg',
    '@everyframeapainting': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCjFqcJQXGZ6T6sxyFB-5i6A',
    '@gigguk': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCOv3Z7230GFKHdACf7zJleg',
    '@halfasinteresting': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC9RM-iSvTu1uPJb8X5yp3EQ',
    '@harvardbusinessreview': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCWo4IA01TXzBeGJJKWHOG9g',
    '@hbomberguy': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCIPqOTYW439-5hUz6r3U1fA',
    '@internetcommentetiquette': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCyWDyupW4lBq95hD0DkG4qg',
    '@internetshaquille': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCOcphUKAnUaair1uZ7SlqiA',
    '@isto_inc': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCgpGbh7d0X3-RBVYC4MQEEw',
    '@johnnyharris': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC7KbIaEOuY7H2j-cvhJ3mYA',
    '@JonasCeikaCCK': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCSkzHxIcfoEr69MWBdo0ppg',
    '@journeytomicrocosmos': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCBbnbBWJtwsf0jLGUwX5Q3g',
    '@kaptainkristian': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCuPgdqQKpq4T4zeqmTelnFg',
    '@kirstendirksen': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCDsElQQt_gCZ9LgnW-7v-cQ',
    '@kurzgesagt': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCq8ZAAsI89IoJ-fn1gYpO3g',
    '@minutephysics': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCeiYXex_fwgYDonaTcSIk6w',
    '@mothersbasement': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCiZhSNqcJqh8uFcY17gatdg',
    '@noclipvideo': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC0fDG3byEcMtbOqPMymDNbw',
    '@numberphile': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCtwKon9qMt5YLVgQt1tvJKg',
    '@patrickhwillems': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCMAwBUlaxyqZY-2hVac8qgg',
    '@pbsspacetime': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCq6OAftTQOuUBRdtUDq5SUA',
    '@sarahzed': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCsLQIZhIhTEskQSRi5y4IOw',
    '@slidebean': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCSGc7c1yKxo-Uhz5_oivrfg',
    '@smartereveryday': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC8VkNBOwvsTlFjoSnNSMmxw',
    '@standupmaths': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCSju5G2aFaWMqn-_0YBtq5A',
    '@stratechery': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC9AHywQeW9BOcOl7dg-YMqA',
    '@theartassignment': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCGaVdbSav8xWuFWTadK6loA',
    '@theendlessadventure': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCVZAfsaiMUbv50gz9TvMrZQ',
    '@theschooloflifeofficial': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC7IcJI8PUf5Z3zKxnZvTBog',
    '@townsends': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCj0yJUTrQvyLDeI3K5PLgyw',
    '@upandatom': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCQALLeQPoZdZC4JNUboVEUg',
    '@veritasium': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCin0m13qWv3-051xlWlHamA',
    '@wisecrack': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC6-PXcR7M7y4S4sB-e7rYSw',
    '@joescott': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCw-J55n8Y5Nn1fB19p0P0uQ',
    '@CuriousArchive': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCP12u_3r8xYlH8o9C42T-5g',
    '@Vsauce': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC6107grRI4m0o2-emgoDnAA',
    '@LEMMiNO': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCRcIdxmu0H1R4qY4s4Z8-3w',
    '@Exurb1a': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC_yP2PkR4oH6jLgUu27C76A',
    '@FredrikKnudsen': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCV19n4922h6m69g0p9LqPxg',
    '@FractalPhilosophy': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCxS4Zl5Y_gW8tU5uN-9_hXw',
    '@Spoogli': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC9Gt9zg0vsmh-21zwVN5epQ',
    '@Wendigoon': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCJkoT4_a87nU0eC_N-2N30A',
    '@BarelySociable': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC9PIn6-XuRKZ5HmYeu46AIw',
    '@AtrocityGuide': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCn8a-VvV-H0P67uO4w8y-eQ',
    '@blameitonjorge': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCU3oAyhHDXjgbxazqOEG2UA',
    '@stevemould': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCEIwxahdLz7bap-VDs9h35A',
    '@CaptainDisillusion': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCVjKN1Y-M98319fJqR1Z1zQ',
    '@EmpLemon': 'https://www.youtube.com/feeds/videos.xml?channel_id=UC7Ucs42FZy3uYzjrqzOIHsw',
    '@JosephAndersonChannel': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCx4u4d03mQ1eWb6T-P-Jk8g',
    '@ContraPoints': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCNvsIonJdJ5E4EXMa65VYpA',
    '@Asianometry': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCnTuW5N0s4a3t87YqQ8t2MA',
    '@CaspianReport': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCp2-2U2m1nE8569lO2293iA',
    '@JCS': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCzXujqv02TfXyG1MhGZlKkA',
    '@NickCrowley': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCM47S9y1qVjWd8W5y84y8yA',
}
