"""
Configuration Module
Contains scraping headers, websites list by topic, and YouTube channels list by topic.
"""

HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5',
    'Referer': 'https://www.google.com/'
}

SITES_BY_TOPIC = {
    '🔬 Science, Discovery & Natural World': [
        ('Quanta Magazine', 'https://www.quantamagazine.org/'),
        ('Science Daily', 'https://www.sciencedaily.com/'),
        ('Science Alert', 'https://www.sciencealert.com/'),
        ('Live Science', 'https://www.livescience.com/'),
        ('The Conversation', 'https://theconversation.com/'),
        ('JSTOR Daily', 'https://daily.jstor.org/'),
        ('Smithsonian Institution', 'https://www.si.edu/'),
        ('HowStuffWorks', 'https://www.howstuffworks.com/'),
        ('Damn Interesting', 'https://www.damninteresting.com/'),
        ('Nautilus Free Articles', 'https://nautil.us/'),
        ('Real Clear Science', 'https://www.realclearscience.com/'),
        ('Phys.org', 'https://phys.org/'),
    ],
    '🚀 Space & Astronomy': [
        ('NASA', 'https://www.nasa.gov/'),
        ('Space.com', 'https://www.space.com/'),
        ('EarthSky', 'https://earthsky.org/'),
        ('Sky & Telescope', 'https://skyandtelescope.org/'),
        ('The Planetary Society', 'https://www.planetary.org/'),
        ('Bad Astronomy (Phil Plait)', 'https://www.syfy.com/syfy-wire/bad-astronomy'),
    ],
    '🧠 Psychology, Behavior & the Mind': [
        ('Psychology Today', 'https://www.psychologytoday.com/'),
        ('Greater Good Magazine', 'https://greatergood.berkeley.edu/magazine'),
        ('BPS Research Digest', 'https://www.bps.org.uk/research-digest'),
        ('Behavioral Scientist', 'https://behavioralscientist.org/'),
        ('Neuroscience News', 'https://neurosciencenews.com/'),
        ('PsyPost', 'https://www.psypost.org/'),
        ('Simoly Psychology', 'https://www.simplypsychology.org/'),
    ],
    '📜 History & Archaeology': [
        ('Ancient History Encyclopedia (World History)', 'https://www.worldhistory.org/'),
        ('The History Blog', 'http://www.thehistoryblog.com/'),
        ('JSTOR Daily', 'https://daily.jstor.org/'),
        ('Archaeology Magazine', 'https://www.archaeology.org/'),
        ('Atlas Obscura', 'https://www.atlasobscura.com/'),
        ('HistoryNet', 'https://www.historynet.com/'),
        ("Lapham's Quarterly", 'https://www.laphamsquarterly.org/'),
    ],
    '💡 Philosophy, Ideas & Critical Thinking': [
        ('The Marginalian', 'https://www.themarginalian.org/'),
        ('Aeon Magazine', 'https://aeon.co/'),
        ('Philosophy Now', 'https://philosophynow.org/'),
        ('Internet Encyclopedia of Philosophy', 'https://iep.utm.edu/'),
        ('Stanford Encyclopedia of Philosophy', 'https://plato.stanford.edu/'),
        ('3 Quarks Daily', 'https://3quarksdaily.com/'),
        ('Farnam Street (FS)', 'https://fs.blog/'),
    ],
    '💰 Economics, Finance & Business': [
        ('Investopedia', 'https://www.investopedia.com/'),
        ('Planet Money (NPR)', 'https://www.npr.org/podcasts/510289/planet-money'),
        ('Marginal Revolution', 'https://marginalrevolution.com/'),
        ('ProMarket', 'https://promarket.org/'),
        ('VoxEU', 'https://cepr.org/voxeu'),
        ('Our World in Data', 'https://ourworldindata.org/'),
        ('Visual Capitalist', 'https://www.visualcapitalist.com/'),
        ('The Hustle', 'https://thehustle.co/'),
    ],
    '🌿 Environment, Climate & Ecology': [
        ('Mongabay', 'https://www.mongabay.com/'),
        ('Carbon Brief', 'https://www.carbonbrief.org/'),
        ('Inside Climate News', 'https://insideclimatenews.org/'),
        ('The Guardian Environment', 'https://www.theguardian.com/environment'),
        ('Yale Environment 360', 'https://e360.yale.edu/'),
        ('Hakai Magazine', 'https://hakaimagazine.com/'),
        ('Ensia', 'https://ensia.com/'),
    ],
    '🏥 Health, Medicine & Nutrition': [
        ('Harvard Health', 'https://www.health.harvard.edu/'),
        ('WebMD', 'https://www.webmd.com/'),
        ('Healthline', 'https://www.healthline.com/'),
        ('MedPage Today', 'https://www.medpagetoday.com/'),
        ('Examine.com', 'https://examine.com/'),
        ('Precision Nutrition', 'https://www.precisionnutrition.com/articles'),
        ('Nih MedlinePlus', 'https://medlineplus.gov/'),
        ('The BMJ (free articles)', 'https://www.bmj.com/'),
    ],
    '💻 Technology, Programming & AI': [
        ('Hacker News', 'https://news.ycombinator.com/'),
        ('MIT Technology Review', 'https://www.technologyreview.com/'),
        ('Ars Technica', 'https://arstechnica.com/'),
        ('The Verge', 'https://www.theverge.com/'),
        ('Wired', 'https://www.wired.com/'),
        ('Stack Overflow Blog', 'https://stackoverflow.blog/'),
        ('Dev.to', 'https://dev.to/'),
        ('CSS-Tricks', 'https://css-tricks.com/'),
        ('Smashing Magazine', 'https://www.smashingmagazine.com/'),
        ('A List Apart', 'https://alistapart.com/'),
        ('Two Minute Papers', 'https://www.youtube.com/c/K%C3%A1rolyZsolnai-Feh%C3%A9r'),
        ('Towards Data Science', 'https://towardsdatascience.com/'),
    ],
    '🔗 Blockchain, Web3 & Crypto': [
        ('CoinDesk', 'https://www.coindesk.com/'),
        ('CoinTelegraph', 'https://cointelegraph.com/'),
        ('Decrypt', 'https://decrypt.co/'),
        ('The Block', 'https://www.theblock.co/'),
        ('Bankless', 'https://www.bankless.com/'),
    ],
    '🎮 Gaming & Game Development': [
        ('Game Developer', 'https://www.gamedeveloper.com/'),
        ('80 Level', 'https://80.lv/'),
        ('Rock Paper Shotgun', 'https://www.rockpapershotgun.com/'),
        ('Polygon', 'https://www.polygon.com/'),
        ('PC Gamer', 'https://www.pcgamer.com/'),
        ('Kotaku', 'https://kotaku.com/'),
        ('Giant Bomb', 'https://www.giantbomb.com/'),
        ('Digital Foundry (Eurogamer)', 'https://www.eurogamer.net/digital-foundry'),
    ],
    '📖 Literature, Fiction & the Written Word': [
        ('Literary Hub', 'https://lithub.com/'),
        ('Reactor (Tor.com)', 'https://reactor.com/'),
        ('Clarkesworld Magazine', 'https://clarkesworldmagazine.com/'),
        ('The Millions', 'https://themillions.com/'),
        ('Electric Literature', 'https://electricliterature.com/'),
        ('Open Culture', 'https://www.openculture.com/'),
        ('Project Gutenberg', 'https://www.gutenberg.org/'),
        ('Standard Ebooks', 'https://standardebooks.org/'),
        ('Anime News Network', 'https://www.animenewsnetwork.com/'),
        ('NovelUpdates', 'https://www.novelupdates.com/'),
    ],
    '🎨 Design, Architecture & Visual Arts': [
        ('Designboom', 'https://www.designboom.com/'),
        ('Dezeen', 'https://www.dezeen.com/'),
        ('Core77', 'https://www.core77.com/'),
        ("It's Nice That", 'https://www.itsnicethat.com/'),
        ('Colossal', 'https://www.thisiscolossal.com/'),
        ('Brain Pickings (The Marginalian)', 'https://www.themarginalian.org/'),
        ('Creative Bloq', 'https://www.creativebloq.com/'),
        ('Behance', 'https://www.behance.net/'),
    ],
    '🎵 Music & Audio': [
        ('NME', 'https://www.nme.com/'),
        ('AV Club', 'https://www.avclub.com/'),
        ('Genius', 'https://genius.com/'),
        ('XXL Magazine', 'https://www.xxlmag.com/'),
        ('Consequence of Sound', 'https://consequence.net/'),
        ('Resident Advisor', 'https://ra.co/'),
        ('The Wire', 'https://www.thewire.co.uk/'),
        ('Sputnikmusic', 'https://www.sputnikmusic.com/'),
    ],
    '🎬 Film, TV & Cinema': [
        ('Little White Lies', 'https://lwlies.com/'),
        ('Roger Ebert (RogerEbert.com)', 'https://www.rogerebert.com/'),
        ('Letterboxd', 'https://letterboxd.com/'),
        ('Screen Rant', 'https://screenrant.com/'),
        ('IndieWire', 'https://www.indiewire.com/'),
        ('Criterion', 'https://www.criterion.com/current'),
        ('Film Comment', 'https://www.filmcomment.com/'),
    ],
    '🍽️ Food, Cooking & Gastronomy': [
        ('Serious Eats', 'https://www.seriouseats.com/'),
        ('The Food Lab (Kenji)', 'https://www.seriouseats.com/the-food-lab'),
        ('Bon Appétit', 'https://www.bonappetit.com/'),
        ('Epicurious', 'https://www.epicurious.com/'),
        ('Eater', 'https://www.eater.com/'),
        ('The Kitchn', 'https://www.thekitchn.com/'),
    ],
    '🌍 Travel, Geography & Culture': [
        ('Atlas Obscura', 'https://www.atlasobscura.com/'),
        ('Nomadic Matt', 'https://www.nomadicmatt.com/'),
        ('Condé Nast Traveler', 'https://www.cntraveler.com/'),
        ('The Culture Trip', 'https://theculturetrip.com/'),
        ('Roads & Kingdoms', 'https://roadsandkingdoms.com/'),
        ('Messy Nessy Chic', 'https://www.messynessy.com/'),
        ('Geo.fr', 'https://www.geo.fr/'),
    ],
    '🏋️ Sports, Fitness & Movement': [
        ('Bleacher Report', 'https://bleacherreport.com/'),
        ('The Athletic', 'https://theathletic.com/'),
        ('FiveThirtyEight', 'https://fivethirtyeight.com/'),
        ('Breaking Muscle', 'https://breakingmuscle.com/'),
        ('Renaissance Periodization', 'https://renaissanceperiodization.com/articles'),
        ('Runners World', 'https://www.runnersworld.com/'),
    ],
    '✏️ Writing, Language & Linguistics': [
        ('The Writing Cooperative', 'https://writingcooperative.com/'),
        ('Grammarist', 'https://grammarist.com/'),
        ('Lingua Franca (Chronicle)', 'https://www.chronicle.com/blogs/linguafranca'),
        ('Language Log', 'https://languagelog.ldc.upenn.edu/nll/'),
        ('The Paris Review — Craft Interviews', 'https://www.theparisreview.org/interviews'),
        ('Austin Kleon', 'https://austinkleon.com/'),
    ],
    '🔢 Mathematics & Logic': [
        ('Quanta Magazine — Math', 'https://www.quantamagazine.org/mathematics/'),
        ('3Blue1Brown', 'https://www.3blue1brown.com/'),
        ('Cut the Knot', 'https://www.cut-the-knot.org/'),
        ('Better Explained', 'https://betterexplained.com/'),
        ('MathWorld (Wolfram)', 'https://mathworld.wolfram.com/'),
        ('AMS Feature Column', 'https://www.ams.org/publicoutreach/feature-column/fc-current'),
    ],
    '🏛️ Politics, Society & Long-form Journalism': [
        ('ProPublica', 'https://www.propublica.org/'),
        ('The Intercept', 'https://theintercept.com/'),
        ('Foreign Policy', 'https://foreignpolicy.com/'),
        ('The Diplomat', 'https://thediplomat.com/'),
        ('Bellingcat', 'https://www.bellingcat.com/'),
        ('Rest of World', 'https://restofworld.org/'),
        ('The Markup', 'https://themarkup.org/'),
    ],
    '🌐 General Knowledge & Curiosity': [
        ('Mental Floss', 'https://www.mentalfloss.com/'),
        ('Curiosity', 'https://www.curiosity.com/'),
        ('The Art of Manliness', 'https://www.artofmanliness.com/'),
        ('Wait But Why', 'https://waitbutwhy.com/'),
        ('Kottke.org', 'https://kottke.org/'),
        ('Longreads', 'https://longreads.com/'),
        ('Pocket (curated)', 'https://getpocket.com/explore'),
        ('Arts & Letters Daily', 'https://www.aldaily.com/'),
    ],
    'Science & Technology': [
        ('Nature', 'https://www.nature.com/'),
        ('Scientific American', 'https://www.scientificamerican.com/'),
        ('New Scientist', 'https://www.newscientist.com/'),
        ('IEEE Xplore', 'https://ieeexplore.ieee.org/'),
        ('Nautilus', 'https://nautil.us/'),
        ('MIT Technology Review', 'https://www.technologyreview.com/'),
    ],
    'Music & Entertainment': [
        ('Pitchfork', 'https://pitchfork.com/'),
        ('Rolling Stone', 'https://www.rollingstone.com/'),
        ('The Athletic', 'https://theathletic.com/'),
        ('Sight & Sound (BFI)', 'https://www.bfi.org.uk/sight-and-sound'),
    ],
}

CHANNELS_BY_TOPIC = {
    'Anime, Manga & Animation': ['@gigguk', '@SuperEyepatchWolf', '@CanipEffect', '@mothersbasement'],
    'Architecture, Design & the Built Environment': ['@NotJustBikes', '@StewartHicks', '@archdigest', '@kirstendirksen', '@TheB1M', '@Vox'],
    'Art, Design & Visual Culture': ['@GreatArtExplained', '@theartassignment', '@CorridorCrew'],
    'Business, Entrepreneurship & Strategy': ['@stratechery', '@ColdFusion', '@HowMoneyWorks', '@slidebean', '@PatrickBoyleOnFinance', '@Wendover'],
    'Comedy, Satire & Wit': ['@hbomberguy', '@internetcommentetiquette', '@drewgooden', '@sarahzed', '@Watcher', '@Wendys'],
    'Computer Science & Programming': ['@Computerphile', '@SebastianLague', '@Fireship', '@TheCodingTrain', '@Reducible', '@TomScottGo'],
    'DIY, Making & Engineering': ['@MarkRober', '@PracticalEngineeringChannel', '@StuffMadeHere', '@AppliedScience', '@WayOutWestBlogstead', '@ThisOldTony'],
    'Economics & Society': ['@EconomicsExplained', '@CGPGrey', '@SecondThought', '@PlanetMoney'],
    'Environment, Climate & Sustainability': ['@OurChangingClimate', '@UndecidedMF', '@JustHaveaThink', '@kurzgesagt', '@Zenura'],
    'Film, Video Essays & Media Criticism': ['@FoldingIdeas', '@patrickhwillems', '@Nerdwriter1', '@everyframeapainting', '@LessonsFromTheScreenplay', '@JustWrite'],
    'Food, Cooking & Culinary Culture': ['@JoshuaWeissman', '@EthanChlebowski', '@internetshaquille', '@TastingHistory', '@KenjisCookingShow', '@FrenchGuyCooking', '@aragusea', '@townsends', '@ItaliaSquisita', '@bingingwithbabish'],
    'Game Design, Gaming Essays & Culture': ['@JacobGeller', '@XboxAhoy', '@GMTK', '@noclipvideo', '@PeopleMakeGames'],
    'Health, Medicine & the Human Body': ['@MedlifeCrisis', '@PrimerBlobs', '@InstituteOfHumanAnatomy', '@WhatIveLearned', '@SciShow', '@DoctorMike'],
    'History, Geopolitics & Geography': ['@Wendover', '@PolyMatter', '@HistoryMatters', '@Toldinstone', '@KingsandGenerals', '@RealEngineering'],
    'Language & Linguistics': ['@TomScottGo', '@Xidnaf', '@NativLang', '@Langfocus', '@Artifexian', '@RobWords'],
    'Mathematics & Logic': ['@3blue1brown', '@numberphile', '@standupmaths', '@Mathologer', '@PrimerBlobs'],
    'Music Theory, History & Analysis': ['@Sideways440', '@AdamNeely', '@12tonevideos', '@RickBeato', '@8bitMusicTheory'],
    'Nature, Biology & the Living World': ['@CrimePaysButBotanyDoesnt', '@journeytomicrocosmos', '@TierZoo', '@smartereveryday', '@SciShow'],
    'Philosophy, Deep Thinking & the Human Condition': ['@Einzelganger', '@theschooloflifeofficial', '@wisecrack', '@academyofideas', '@LikeStoriesofOld'],
    'Physics, Science & the Universe': ['@veritasium', '@kurzgesagt', '@pbsspacetime', '@minutephysics', '@upandatom', '@AntonPetrov'],
    'Psychology, Behavior & the Mind': ['@Psych2go', '@kurzgesagt', '@MedlifeCrisis', '@TEDEd'],
    'Storytelling, Narrative & Long-Form Essays': ['@TomScottGo', '@CGPGrey', '@OverlySarcasticProductions', '@kaptainkristian', '@hbomberguy'],
    'Travel, Places & Urban Life': ['@Wendover', '@NotJustBikes', '@AbroadinJapan', '@theendlessadventure', '@baldandbankrupt', '@halfasinteresting', '@KentoBento', '@johnnyharris'],
    'True Crime, Mysteries & Investigation': ['@bellingcatofficial', '@InternetHistorian', '@LegalEagle', '@Nexpo']
}
